name = "bilder-site"
compatibility_date = "2026-04-05"

[[d1_databases]]
binding = "DB"
database_name = "bilder-likes"
database_id = "REPLACE_WITH_D1_DATABASE_ID"

[env.preview]
name = "bilder-site-preview"
compatibility_date = "2026-04-05"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "bilder-likes-preview"
database_id = "REPLACE_WITH_PREVIEW_D1_DATABASE_ID"
